apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cf24ud3hz-nodejs 
  janus-idp.io/tekton: cf24ud3hz-nodejs
  backstage.io/kubernetes-id: cf24ud3hz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cf24ud3hz-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  