apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cf24ud3hz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cf24ud3hz-nodejs 
  name: cf24ud3hz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cf24ud3hz-nodejs 
